spring:
  application:
    name: OrderService
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3306/order_service
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8081